[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# Localization color

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "red = G.C.RED,"
position = "before"
payload = "evo = G.C.RARITY['evo'],"
match_indent = true


# Add amount tooltip to vanilla joker

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if specific_vars and specific_vars.pinned then info_queue[#info_queue+1] = {key = 'pinned_left', set = 'Other'} end"
position = "before"
payload = """
if has_evo(_c) then info_queue[#info_queue + 1] = set_evo_tooltip(_c) end
"""
match_indent = true


# Add evolution attributes

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.added_to_deck = true"
position = "after"
payload = """
evo = self:get_card_evolution()
if self.ability.set == "Joker" and evo then
	self.ability.can_evolve = false
    self.ability.amount = evo.amount
end
"""
match_indent = true


# Superstar main_end text

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Joker' then loc_vars = {self.ability.mult}"
position = "after"
payload = """
evo = self:get_card_evolution()
elseif self.ability.name == "Superstar" then
	local has_message= (G.GAME and self.area and (self.area == G.jokers))
    if has_message then
        local disableable = G.GAME.blind and ((not G.GAME.blind.disabled) and (G.GAME.blind:get_type() == 'Boss'))
        main_end = {
            {n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={
                {n=G.UIT.C, config={ref_table = self, align = "m", colour = disableable and G.C.GREEN or G.C.RED, r = 0.05, padding = 0.06}, nodes={
                    {n=G.UIT.T, config={text = ' '..localize(disableable and 'k_active' or 'ph_no_boss_active')..' ',colour = G.C.UI.TEXT_LIGHT, scale = 0.32*0.9}},
                }}
            }}
        }
    end
"""
match_indent = true


# Pre_reroll context

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "ease_dollars(-G.GAME.current_round.reroll_cost)"
position = "after"
payload = """
for i = 1, #G.jokers.cards do
    G.jokers.cards[i]:calculate_joker({je_prereroll_shop = true})
end
"""
match_indent = true

# Calculate "Idea" joker

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if context.open_booster then"
position = "before"
payload = """
if self.ability.name == "Idea" then
    local other_joker = G.jokers.cards[#G.jokers.cards]
    if other_joker and other_joker ~= self then
        context.blueprint = (context.blueprint and (context.blueprint + 1)) or 1
        context.blueprint_card = context.blueprint_card or self
        if context.blueprint > #G.jokers.cards + 1 then return end
        local other_joker_ret = other_joker:calculate_joker(context)
        if other_joker_ret then 
            other_joker_ret.card = context.blueprint_card or self
            other_joker_ret.colour = G.C.RED
            return other_joker_ret
        end
    end
end
"""
match_indent = true

# "Idea" joker compatibility 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Brainstorm' then"
position = "before"
payload = """
elseif self.ability.name == 'Idea' then
    self.ability.blueprint_compat_ui = self.ability.blueprint_compat_ui or ''; self.ability.blueprint_compat_check = nil
    main_end = (self.area and self.area == G.jokers) and {
        {n=G.UIT.C, config={align = "bm", minh = 0.4}, nodes={
            {n=G.UIT.C, config={ref_table = self, align = "m", colour = G.C.JOKER_GREY, r = 0.05, padding = 0.06, func = 'blueprint_compat'}, nodes={
                {n=G.UIT.T, config={ref_table = self.ability, ref_value = 'blueprint_compat_ui',colour = G.C.UI.TEXT_LIGHT, scale = 0.32*0.8}},
            }}
        }}
    } or nil
"""
match_indent = true

# "Idea" joker compatibility 2

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Blueprint' or self.ability.name == 'Brainstorm' then"
position = "before"
payload = """
if self.ability.name == 'Idea' then
    local other_joker = G.jokers.cards[#G.jokers.cards]
    if other_joker and other_joker ~= self and other_joker.config.center.blueprint_compat then
        self.ability.blueprint_compat = 'compatible'
    else
        self.ability.blueprint_compat = 'incompatible'
    end
end
"""
match_indent = true